### ISSUE TITLE
Card assets

### ISSUE THREAD

**Issue by thomastuts** [exane/gwent-online#1]
Hey there! Cool project, I'm also working on a Gwent web version to sharpen my skills. I was just wondering how you managed to get those card assets. Did you extract them from the game files, or did you screenshot all of them?

Would it be cool if I used these in my own project too? Right now I'm using screenshots of the cards scraped from gosunoob.com, but their resolution and quality varies greatly. Yours somehow look much crisper.

**Comment by exane** [comment]
Hey! 

Funny think you mentioned the assets. I thought, until now, they were also from gosunoob.com. 
I was initially looking for any assets I could use in this project (was in the very beginning) and I just took the next best assets I found. So no, I neither extracted nor did screenshot them.  
My source of the card assets are from https://github.com/kgsherman/gwentjs

**Comment by thomastuts** [comment]
Awesome, thanks for the quick reply!
